version: '3.8'

services:
  webserver:
    image: php:7.4-apache
    container_name: php_webserver
    ports:
      - "8080:80" # Expose le serveur web sur le port 8080
    volumes:
      - ./web:/var/www/html/ # Monte le répertoire local `web` dans le conteneur
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    volumes:
      - ./mysql_data:/var/lib/mysql # Volume pour persister les données MySQL
    networks:
      - mynetwork
    ports:
      - "3306:3306" # Expose le port MySQL sur l'hôte

networks:
  mynetwork:
    driver: bridge
