version: '3.8'

services:
  webserver:
    image: php:7.4-apache
    container_name: php_webserver
    ports:
      - "8080:80" # Open the port 8080
    volumes:
      - ./web:/var/www/html/
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    container_name: mysql_database
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - mynetwork
    ports:
      - "3306:3306" # Open the port 3306

networks:
  mynetwork:
    driver: bridge
