version: '1'
services:
  webserver:
    container_name: apache_webserver
    ports:
      - "8080:80"       # Redirige le port 80 du conteneur vers le port 8080 de l'hôte
    networks:
      - mynetwork
    build: 
      context: ./webserver
      dockerfile: Dockerfile
    volumes:
      - ./webserver/php:/var/www/html/

  mysql:
    container_name: mysql_database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin      # Mot de passe pour l'utilisateur root
      MYSQL_DATABASE: example_db      # Nom de la db
      MYSQL_USER: user                # Utilisateur de la db
      MYSQL_PASSWORD: 123             # Mot de passe de l'utilisateur
    networks:
      - mynetwork
    build: 
      context: ./sql
      dockerfile: Dockerfile
    volumes:
      - ./mysql_data:/var/lib/mysql   # Volume pour persister les données

networks:
  mynetwork:
    driver: bridge    # Utilise un réseau bridge pour connecter les deux conteneurs

volumes:
  mysql_data:
    driver: local     # Volume local pour stocker les données MySQL